# " | " real world example in a k8s config file

apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config-file
data:
  mosquitto-conf: |
    log_dest stdout
    log_type all
    log_timestamp true
    listener 9001
